name: Test

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm i

      - name: Run the tests
        run: npm run test:coverage

      - name: Submit coverage data to codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unit
          token: ${{ secrets.CODECOV_TOKEN }}

  integration:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [ 14, 16 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Run the tests
        run: npm run test:coverage

      - name: Submit coverage data to codecov
        uses: codecov/codecov-action@v3
        with:
          flags: integration
          token: ${{ secrets.CODECOV_TOKEN }}

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm i

      - name: Run the tests
        run: npm run test:coverage

      - name: Submit coverage data to codecov
        uses: codecov/codecov-action@v3
        with:
          flags: windows
          token: ${{ secrets.CODECOV_TOKEN }}
